export const dummyProducts = [
    {
      productId: 90,
      tags: null,
      defaultSku: "ABC-121",
      name: "test shirt",
      subheading: "test heading",
      description: "test des",
      groupCompanyId: 1,
      companyId: 1,
      locationId: 1,
      branchId: 1,
      status: "active",
      attributes: [
        {
          sku: "ABC-121",
          imgs: [
            {
              img_Id: 1740051162285,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051162285-blue-1.jpg",
              img_name: "blue-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "S",
          color: "Navy-000080",
          price: 120,
          keyName: "",
          pattern: "Solid",
          quantity: 5,
        },
        {
          sku: "ABC-122",
          imgs: [
            {
              img_Id: 1740051162285,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051162285-blue-1.jpg",
              img_name: "blue-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "M",
          color: "Navy-000080",
          price: 120,
          pattern: "Solid",
          quantity: 86,
        },
        {
          sku: "DEF-121",
          imgs: [
            {
              img_Id: 1740051202835,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051202835-maroon-1.jpg",
              img_name: "maroon-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "L",
          color: "Maroon-800000",
          price: 150,
          pattern: "Solid",
          quantity: 50,
        },
        {
          sku: "DEF-122",
          imgs: [
            {
              img_Id: 1740051202835,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051202835-maroon-1.jpg",
              img_name: "maroon-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "S",
          color: "Maroon-800000",
          price: 155,
          pattern: "Solid",
          quantity: 70,
        },
      ],
      createdDate: "2025-02-20T17:04:35.799",
      productType: {
        id: 1,
        productType: "Shirt",
        groupCompanyId: 1,
        companyId: 1,
        categoryMappingId: 1,
      },
      lowStockThreshold: null,
    },
    {
      productId: 91,
      tags: null,
      defaultSku: "ABC-221",
      name: "test shirt 2",
      subheading: "test heading 2",
      description: "test des 2",
      groupCompanyId: 1,
      companyId: 1,
      locationId: 1,
      branchId: 1,
      status: "active",
      attributes: [
        {
          sku: "ABC-221",
          imgs: [
            {
              img_Id: 1740051162285,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051162285-blue-1.jpg",
              img_name: "blue-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "S",
          color: "Navy-000080",
          price: 1,
          keyName: "",
          pattern: "Solid",
          quantity: 136,
        },
        {
          sku: "ABC-222",
          imgs: [
            {
              img_Id: 1740051162285,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051162285-blue-1.jpg",
              img_name: "blue-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "M",
          color: "Navy-000080",
          price: 120,
          pattern: "Solid",
          quantity: 31,
        },
        {
          sku: "DEF-221",
          imgs: [
            {
              img_Id: 1740051202835,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051202835-maroon-1.jpg",
              img_name: "maroon-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "L",
          color: "Maroon-800000",
          price: 150,
          pattern: "Solid",
          quantity: 18,
        },
        {
          sku: "DEF-222",
          imgs: [
            {
              img_Id: 1740051202835,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740051202835-maroon-1.jpg",
              img_name: "maroon-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "S",
          color: "Maroon-800000",
          price: 155,
          pattern: "Solid",
          quantity: 123,
        },
      ],
      createdDate: "2025-02-20T17:07:33.304",
      productType: {
        id: 1,
        productType: "Shirt",
        groupCompanyId: 1,
        companyId: 1,
        categoryMappingId: 1,
      },
      lowStockThreshold: null,
    },
    {
      productId: 92,
      tags: null,
      defaultSku: "SKU-002",
      name: "new shirt",
      subheading: "new shirt heading",
      description: "this is dummy description for new shirt",
      groupCompanyId: 1,
      companyId: 1,
      locationId: 1,
      branchId: 1,
      status: "active",
      attributes: [
        {
          fit: "Oversized",
          sku: "SKU-005",
          imgs: [
            {
              img_Id: 1740119419171,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740119419171-red-1.jpg",
              img_name: "red-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "S",
          color: "Red-FF0000",
          price: 330,
          pattern: "Solid",
          quantity: 29,
        },
        {
          fit: "Slim",
          sku: "SKU-007",
          imgs: [
            {
              img_Id: 1740119419171,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740119419171-red-1.jpg",
              img_name: "red-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "XL",
          color: "Red-FF0000",
          price: 350,
          pattern: "Printed",
          quantity: 46,
        },
        {
          fit: "Regular",
          sku: "SKU-006",
          imgs: [
            {
              img_Id: 1740119419171,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740119419171-red-1.jpg",
              img_name: "red-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "XS",
          color: "Red-FF0000",
          price: 420,
          pattern: "Checked",
          quantity: 30,
        },
        {
          fit: "Slim",
          sku: "SKU-002",
          imgs: [
            {
              img_Id: 1740118980373,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740118980373-blue-1.jpg",
              img_name: "blue-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "M",
          color: "Navy-000080",
          price: 470,
          pattern: "Striped",
          quantity: 86,
        },
        {
          fit: "Slim",
          sku: "SKU-004",
          imgs: [
            {
              img_Id: 1740119361068,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740119361068-gree-2.jpg",
              img_name: "gree-2.jpg",
              img_type: "jpeg",
            },
          ],
          size: "S",
          color: "Green-008000",
          price: 470,
          pattern: "Printed",
          quantity: 11,
        },
        {
          fit: "Regular",
          sku: "SKU-001",
          imgs: [
            {
              img_Id: 1740118980373,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740118980373-blue-1.jpg",
              img_name: "blue-1.jpg",
              img_type: "jpeg",
            },
          ],
          size: "S",
          color: "Navy-000080",
          price: 510,
          keyName: "",
          pattern: "Solid",
          quantity: 68,
        },
        {
          fit: "Relaxed",
          sku: "SKU-003",
          imgs: [
            {
              img_Id: 1740119361068,
              img_url: "https://actifylms.blob.core.windows.net/cms/ecom/1740119361068-gree-2.jpg",
              img_name: "gree-2.jpg",
              img_type: "jpeg",
            },
          ],
          size: "L",
          color: "Green-008000",
          price: 510,
          pattern: "Plaid",
          quantity: 25,
        },
      ],
      createdDate: "2025-02-21T12:04:06.064",
      productType: {
        id: 1,
        productType: "Shirt",
        groupCompanyId: 1,
        companyId: 1,
        categoryMappingId: 1,
      },
      lowStockThreshold: null,
    },
  ]
  
  